paths:
  /api/products/:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        "200" :
          description: Productos obtenidos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500" :
          description: Error interno del servidor al obtener los usuarios

  /api/products/{id}:
        get:
            summary: Obtener un producto por su id
            tags:
                - Products
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      $type: String
                  description: Id del producto a buscar
            responses:
                '200':
                    description: Producto obtenido satisfactoriamente
                    content:
                        application/json:
                            schema:
                                type: Object
                                $ref: '#/components/schemas/Product'
                '404':
                    description: Producto no encontrado
                '500':
                    description: Error interno del servidor al consultar producto

components:
    schemas:
        Product:
            type: object
            properties:
                _id:
                    type: ObjectId
                    description: Id autogenerado de MongoDB
                title:
                    type: String
                    description: Nombre del producto
                description:
                    type: String
                    description: Descripcion del producto
                category:
                    type: String
                    description: Categoria a la que pertenece el producto
                price:
                    type: Number
                    description: Precio del producto
                stock:
                    type: Number
                    description: Cantidad de productos disponibles
                code:
                    type: String
                    description: Codigo unico del producto
                status:
                    type: Boolean
                    description: Existe (true), no existe (false). -Opcional-
            example:
                _id: ObjectId('456489489465')
                title: Televisor
                description: Televisor Philips
                category: Electronica
                price: 433333
                stock: 233
                code: 12233a
                status: true
        